# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Nishad Singhi
first_name: Nishad
middle_name: 
last_name: Singhi
email: nishadsinghi@gmail.com
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

lang: en
icon: ⚛️

url: https://nishadsinghi.github.io
baseurl: 
last_updated: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 800px

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: nishadsinghi
twitter_username: nishadsinghi
linkedin_username: nishadsinghi
scholar_userid: L1b6JqsAAAAJ

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
  - _posts/2020-09-28-twitter.md
  - _posts/2021-07-04-diagrams.md
  - _posts/2023-07-04-jupyter-notebook.md

# Minimal plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-toc
  - jekyll/scholar

# Pagination
pagination:
  enabled: true

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Announcements
announcements:
  enabled: true
  scrollable: true
  limit: 5

# Latest posts
latest_posts:
  enabled: false
  scrollable: true
  limit: 3

# Publications
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Einstein]
  first_name: [Albert, A.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending 